@URL={{BASE_URL}}/token/connect

### Get by logined
POST {{ URL }}
Content-Type: application/json

{
    "apiKey": "de3ff24f-9c02-4f26-848a-652b3c2af980",
    "secretKey": "d78bf3f2-6e28-4042-83ab-eb2d86bab00a",
    "grantType": "password"
}

# {
#     "apiKey": "8ddc8b58-f3f6-4e14-8acb-51f360956388",
#     "secretKey": "ff255589-76b0-4d5d-9d12-7b855ab8071e",
#     "grantType": "password"
# }



