@URL={{BASE_URL}}/return/search

### Validate params
GET {{ URL }}?limit=-10&page=a&keywork=a
Authorization: Bearer {{ TOKEN }}
Content-Type: application/json

{
}

### No Params
GET {{ URL }}
Authorization: Bearer {{ TOKEN }}
Content-Type: application/json

{
}

### With Keyword
GET {{ URL }}/?page=99999999999999999999999
Authorization: Bearer {{ TOKEN }}
Content-Type: application/json

{
}