version: "3"

services:
  jenkins:
    build:
      context: .
    container_name: jenkins
    privileged: true
    restart: always
    ports:
      - 38080:8080
    volumes:
      - jenkins-data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  jenkins-data:
