@URL={{BASE_URL}}/order/search

### Validate params
GET {{ URL }}?limit=10&page=2
Authorization: Bearer {{ TOKEN }}
Content-Type: application/json

{
}

### No Params
GET {{ URL }}
Authorization: Bearer {{ TOKEN }}
Content-Type: application/json

{
}

### With Keyword
GET {{ URL }}/?limit=10000&page=1&keyword=&status=2000
Authorization: Bearer {{ TOKEN }}
Content-Type: application/json

{
}