apiVersion: apps/v1
kind: Deployment
metadata:
  name: egi-laravel-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: egi-laravel
  template:
    metadata:
      labels:
        app: egi-laravel
    spec:
      containers:
      - name: egi-laravel
        image: docker.io/doannq01/laravel-learn-k8s
        ports:
        - containerPort: 8000
          name: egi-laravel
