apiVersion: v1
kind: Service
metadata:
  name: egi-laravel-service
spec:
  selector:
    app: egi-laravel
  ports:
  - name: egi-laravel
    port: 8000
    targetPort: 8000
    nodePort: 30900
  type: NodePort
