@URL={{BASE_URL}}/merchant/

### FUll
PUT {{ URL }}
Authorization: Bearer {{ TOKEN }}
Content-Type: application/json

{
    "businessName": "Intrepid Carlsberg",
    "arcaNo": "201839023M-1",
    "ownerContactOffice": "+6588888888",
    "ownerPhoneNumber": "+6588888888",
    "companyPrefix": "CAR",
    "merchantType": "Business",
    "registeredAddress": {
      "country": "Singapore",
      "state": "Singapore",
      "city": "Singapore",
      "postalCode": "068898",
      "street1": "80 Robinson Road",
      "street2": null,
      "building": null,
      "blockNumber": null,
      "unitNumber": "02-00"
    },
    "billingAddress": {
      "country": "Singapore",
      "state": "Singapore",
      "city": "Singapore",
      "postalCode": "068898",
      "street1": "80 Robinson Road",
      "street2": null,
      "building": null,
      "blockNumber": null,
      "unitNumber": "#02-00"
    },
    "contactPerson": {
      "firstName": "Peter",
      "middleName": "Cola",
      "lastName": "Miclat",
      "email": "tom@example.com",
      "phoneNumber": "+6591872128",
      "contactOffice": "+6591872128"
    },
    "billingPerson": {
      "firstName": "Peter",
      "middleName": "Sail",
      "lastName": "Miclat",
      "email": "tom@example.com",
      "phoneNumber": "+6591872128",
      "contactOffice": "+6591872128"
    }
}

### Only businessName
PUT {{ URL }}
Authorization: Bearer {{ TOKEN }}
Content-Type: application/json

{
    "businessName": "MAI LAN _TUAN"
}


### bỏ registeredAddress
PUT {{ URL }}
Authorization: Bearer {{ TOKEN }}
Content-Type: application/json

{
    "businessName": "MAI LAN _TUAN",
    "ownerContactOffice": "+84987654321",
    "ownerPhoneNumber": "+84987654321",
    "billingAddress": {
        "country": "Vietnam",
        "state": "HCM",
        "city": "HCM",
        "postalCode": "123123",
        "street1": "District 1",
        "street2": "District 1",
        "building": "District 1",
        "blockNumber": "District 2",
        "unitNumber": null
    },
    "contactPerson": {
        "firstName": "Thang",
        "middleName": "Huynh",
        "lastName": "Nguyen",
        "email": "thang-merchant-1@zto.com",
        "phoneNumber": "+84987654321",
        "contactOffice": "+84123456789"
    },
    "billingPerson": {
        "firstName": "Thang",
        "middleName": "Huynh",
        "lastName": "Nguyen",
        "email": "thang-merchant-1@zto.com",
        "phoneNumber": "+84987654321",
        "contactOffice": "+84123456789"
    }
}

### registeredAddress thiếu value
PUT {{ URL }}
Authorization: Bearer {{ TOKEN }}
Content-Type: application/json

{
    "businessName": "MAI LAN _TUAN",
    "ownerContactOffice": "+84987654321",
    "ownerPhoneNumber": "+84987654321",
    "registeredAddress": {
        "postalCode": "123123",
        "street1": "District 1",
        "street2": "District 1",
        "building": "District 1",
        "blockNumber": "District 1",
        "unitNumber": null
    },
    "billingAddress": {
        "country": "Vietnam",
        "state": "HCM",
        "city": "HCM",
        "postalCode": "123123",
        "street1": "District 1",
        "street2": "District 1",
        "building": "District 1",
        "blockNumber": "District 1",
        "unitNumber": null
    },
    "contactPerson": {
        "firstName": "Thang",
        "middleName": "Huynh",
        "lastName": "Nguyen",
        "email": "thang-merchant-1@zto.com",
        "phoneNumber": "+84987654321",
        "contactOffice": "+84123456789"
    },
    "billingPerson": {
        "firstName": "Thang",
        "middleName": "Huynh",
        "lastName": "Nguyen",
        "email": "thang-merchant-1@zto.com",
        "phoneNumber": "+84987654321",
        "contactOffice": "+84123456789"
    }
}

### RegisteredAddress Có null
PUT {{ URL }}
Authorization: Bearer {{ TOKEN }}
Content-Type: application/json

{
    "businessName": "MAI LAN _TUAN",
    "ownerContactOffice": "+84987654321",
    "ownerPhoneNumber": "+84987654321",
    "registeredAddress": {
        "country": null,
        "state": null,
        "city": "HCM",
        "postalCode": "123123",
        "street1": "District 1",
        "street2": "District 1",
        "building": "District 1",
        "blockNumber": "District 1",
        "unitNumber": null
    },
    "billingAddress": {
        "country": "Vietnam",
        "state": "HCM",
        "city": "HCM",
        "postalCode": "123123",
        "street1": "District 1",
        "street2": "District 1",
        "building": "District 1",
        "blockNumber": "District 1",
        "unitNumber": null
    },
    "contactPerson": {
        "firstName": null,
        "middleName": "Huynh",
        "lastName": "Nguyen",
        "email": "thang-merchant-1@zto.com",
        "phoneNumber": "+84987654321",
        "contactOffice": "+84123456789"
    },
    "billingPerson": {
        "firstName": "Thang",
        "middleName": "Huynh",
        "lastName": "Nguyen",
        "email": "thang-merchant-1@zto.com",
        "phoneNumber": "+84987654321",
        "contactOffice": "+84123456789"
    }
}

### Test Validate
PUT {{ URL }}
Authorization: Bearer {{ TOKEN }}
Content-Type: application/json

{
    "businessName": "MA",
    "ownerContactOffice": "1",
    "ownerPhoneNumber": "1",
    "registeredAddress": {
        "country": "1",
        "state": "1",
        "city": "1",
        "postalCode": "123123",
        "street1": "District 1",
        "street2": "District 1",
        "building": "District 1",
        "blockNumber": "District 1",
        "unitNumber": null
    },
    "billingAddress": {
        "country": "Vietnam",
        "state": "HCM",
        "city": "HCM",
        "postalCode": "123123",
        "street1": "District 1",
        "street2": "District 1",
        "building": "District 1",
        "blockNumber": "District 1",
        "unitNumber": null
    },
    "contactPerson": {
        "firstName": "1",
        "middleName": "1",
        "lastName": "1",
        "email": "to.com",
        "phoneNumber": "1",
        "contactOffice": "+1"
    },
    "billingPerson": {
        "firstName": "Thang",
        "middleName": "Huynh",
        "lastName": "Nguyen",
        "email": "thang-merchant-1@zto.com",
        "phoneNumber": "+84987654321",
        "contactOffice": "+84123456789"
    }
}