

version: "3"
services:
  egiwork:
    image: leduccuong01/egiwork-web-v1
    container_name: egiwork
    privileged: true
    restart: always
    ports:
      - 8000:80
    environment:
        SECRETFOLDER: 'local'
        APPENV: 'local'
        CONTAINER: 'BACKEND'
    volumes:
        - './data/:/var/www/html/'          
