### GET MERCHANT
GET {{BASE_URL}}/merchant
Authorization: Bearer {{ TOKEN }}
Content-Type: application/json

{
}

### UPDATE MERCHANT
PUT {{ BASE_URL }}/merchant/
Authorization: Bearer {{ TOKEN }}
Content-Type: application/json

{
    "businessName": "Intrepid Carlsberg",
    "arcaNo": "201839023M-1",
    "ownerContactOffice": "+6588888888",
    "ownerPhoneNumber": "+6588888888",
    "companyPrefix": "CAR",
    "merchantType": "Business",
    "registeredAddress": {
      "country": "Singapore",
      "state": "Singapore",
      "city": "Singapore",
      "postalCode": "068898",
      "street1": "80 Robinson Road",
      "street2": null,
      "building": null,
      "blockNumber": null,
      "unitNumber": "02-00"
    },
    "billingAddress": {
      "country": "Singapore",
      "state": "Singapore",
      "city": "Singapore",
      "postalCode": "068898",
      "street1": "80 Robinson Road",
      "street2": null,
      "building": null,
      "blockNumber": null,
      "unitNumber": "#02-00"
    },
    "contactPerson": {
      "firstName": "Peter",
      "middleName": "Cola",
      "lastName": "Miclat",
      "email": "tom@example.com",
      "phoneNumber": "+6591872128",
      "contactOffice": "+6591872128"
    },
    "billingPerson": {
      "firstName": "Peter",
      "middleName": "Sail",
      "lastName": "Miclat",
      "email": "tom@example.com",
      "phoneNumber": "+6591872128",
      "contactOffice": "+6591872128"
    }
}

### CREATE ORDER
POST {{ BASE_URL }}/order/bulk-create
Authorization: Bearer {{ TOKEN }}
Content-Type: application/json

{
    "create": [
        {
            "orderNumber": "D-1204-02",
            "deliveryDate": "2023-04-24",
            "cashOnDeliveryAmount": 3,
            "isDoCollection": true,
            "isExchange": true,
            "trackingNumber": "CARCAR152419837",
            "shippingLabelUrl": "http://example.com",
            "courier": "ZTOSG",
            "marketplace": "ZTOSG",
            "remarks": "987967567",
            "orderLineItems": [
                {
                    "sku": "4330104",
                    "lineNumber": "Line-01",
                    "price": 1000,
                    "quantity": 1
                }
            ],
            "recipientInformation": {
                "recipientEmail": "tom@example.com",
                "recipientName": "Peter",
                "recipientNumber": "+6588888888",
                "recipientAddress": "Sin Ming Lane",
                "recipientCity": "Midview",
                "recipientState": "Midview",
                "recipientCountry": "SG",
                "recipientPostalCode": "573960"
            }
        }
    ]
}

### GET LIST
GET {{BASE_URL}}/order/search/?limit=10&page=1&keyword=&status=2000
Authorization: Bearer {{ TOKEN }}
Content-Type: application/json

{
}

### GET BY ID
GET {{BASE_URL}}/order/f8a15266-d7d0-47e4-b2bd-508c717033fbee
Authorization: Bearer {{ TOKEN }}
Content-Type: application/json

{
}

### CANCEL ORDER
PUT {{ BASE_URL }}/order/f8a15266-d7d0-47e4-b2bd-508c717033fb/cancel
Authorization: Bearer {{ TOKEN }}
Content-Type: application/json

{
    "remarks": "1111"
}

### UPDATE ORDER
PUT {{ BASE_URL }}/order/f8a15266-d7d0-47e4-b2bd-508c717033fb
Authorization: Bearer {{ TOKEN }}
Content-Type: application/json

{
    "deliveryDate": "2023-08-24",
    "marketplace": "ZTOSG",
    "trackingNumber": 26,
    "cashOnDeliveryAmount": 2,
    "courier": "ZTOSG",
    "statusText": "reserved",
    "remarks": "987967567",
    "isDoCollection": false,
    "isExchange": false,
    "recipientInformation": {
        "recipientEmail": "tom@example.com",
        "recipientName": "Peter",
        "recipientNumber": "+6588888888",
        "recipientAddress": "Sin Ming Lane",
        "recipientCity": "Midview",
        "recipientState": "Midview",
        "recipientCountry": "SG",
        "recipientPostalCode": "573960"
    }
}