apiVersion: v1
kind: Pod
metadata:
  name: mysql-data-access
spec:
  containers:
    - name: mysql-client
      image: mysql:latest
      command: ["sleep", "infinity"]
      volumeMounts:
        - name: mysql-persistent-storage
          mountPath: ./data
  volumes:
    - name: mysql-persistent-storage
      persistentVolumeClaim:
        claimName: mysql-pv-claim
