apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phpmyadmin
  template:
    metadata:
      labels:
        app: phpmyadmin
    spec:
      containers:
      - name: phpmyadmin
        image: phpmyadmin:latest
        env:
        - name: PMA_HOST
          value: "mysql-service"
        - name: PMA_USER
          value: "doannq_db"
        - name: PMA_PASSWORD
          value: "Aa!@#123"
        ports:
        - containerPort: 80
          name: phpmyadmin