name: Egi Learn K8s

on: 
  push:
    branches: [ master ]

env:
  IMAGE_NAME: doannq01/laravel-learn-k8s
  DOCKER_USERNAME: doannq01
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  WORK_DIR: day-04/laravel-app 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Install Composer
      run: |
        ls
        composer --version
        composer install
      working-directory: ${{ env.WORK_DIR }}

    - name: Build Docker Image
      run: |
        docker build -t laravel-app:${{ github.sha }} .
        docker images
      working-directory: ${{ env.WORK_DIR }}
      
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ env.DOCKER_USERNAME }}
        password: ${{ env.DOCKER_PASSWORD }}
        
    - name: Push Docker Image
      run: |
        docker push -t laravel-app:${{ github.sha }} .
        docker images
