name: Laravel CI

on: 
  push:
    branches: [ master ]

env:
  IMAGE_NAME: laravel-app
  DOCKER_USERNAME: doannq01@gmail.com
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Change directory to day-04
      run: cd day-04/laravel-app

    - name: Install Composer
      run: |
        php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
        php composer-setup.php --install-dir=bin --filename=composer

    - name: Build Docker Image
      run: |
        docker build -t laravel-app:${{ github.sha }} .
        docker images
