name: Laravel CI

on: 
  push:
    branches: [ master ]

env:
  IMAGE_NAME: laravel-app
  DOCKER_USERNAME: doannq01@gmail.com
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  WORK_DIR: day-04/laravel-app 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Composer
      run: |
        ls
        composer --version
      working-directory: ${{ env.WORK_DIR }}

    - name: Build Docker Image
      run: |
        docker build -t laravel-app:${{ github.sha }} .
        docker images
      working-directory: ${{ env.WORK_DIR }}
